apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "serviceNameEnv" $ }}-secret"
type: Opaque
data:
{{- if $.Values.service.secret }}
  {{- range $key, $value := $.Values.service.secret }}
  {{ $key }}: "{{ $value | b64enc }}"
  {{- end }}
{{- end }}
